syntax on 
filetype on
filetype plugin on
filetype indent on
set nocompatible
set number
set shiftwidth=4
set tabstop=4
set expandtab
set nobackup
set scrolloff=10
set wrap
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set wildmenu
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.exe,*.flv,*.img,*.xlsx
set mouse=a
set guicursor=
set noerrorbells
set tabstop=2 softtabstop=2
set expandtab
set smartindent
set noswapfile
set undofile
set nu
set updatetime=50
set shortmess+=c
set rtp+=~/.vim/bundle/Vundle.vim
set noshowmode
set backspace=indent,eol,start
let python_highlight_all = 1 
let g:jedi#auto_initialization = 1


call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'morhetz/gruvbox'
Plugin 'preservim/nerdtree'
Plugin 'unkiwii/vim-nerdtree-sync'
Plugin 'kyoz/purify', { 'rtp': 'vim' }
Plugin 'jiangmiao/auto-pairs'
Plugin 'davidhalter/jedi-vim'
Plugin 'itchyny/lightline.vim'
call vundle#end()

call plug#begin()
Plug 'vimsence/vimsence'
call plug#end()

set laststatus=2
colorscheme purify
set bg=dark

map <silent> <C-l> :NERDTreeFocus<CR>

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }

